# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta4
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - context: .
    image: nodejs-hello-world
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/**
portForward:
  - resourceName: nodejs-hello-world
    localPort: 8080
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
